### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazonaws/services/dynamodbv2/model/transform/LimitExceededExceptionUnmarshaller

### ISSUE THREAD

**Issue by eswenson1** [sclasen/akka-persistence-dynamodb#13]
I'm using "com.amazonaws" % "aws-java-sdk" % "1.10.12" in my project, as well as "com.sclasen" %% "akka-persistence-dynamodb" % "0.3.4". Attempt to start up the akka persistent backend raise a NoClassDefFoundError exception referencing com/amazonaws/services/dynamodbv2/model/transform/LimitExceededExceptionUnmarshaller.

Apparently this transform no longer exists in 1.10.12 of the AWS DynamoDB SDK.  It seems akka-persistence-dynamodb is relying on an old AWS SDK ("com.amazonaws" % "aws-java-sdk" % "1.8.9.1").

**Comment by rkuhn** [comment]
This will soon be solved once the upgrade to Akka 2.4.1 is done—at the new home of this plugin under the Akka organization, see https://github.com/akka/akka-persistence-dynamodb.

**Comment by sclasen** [comment]
:+1:  closing, please re-open if there are further questions.
