### ISSUE TITLE
Tag the git commits with the release versions

### ISSUE THREAD

**Issue by neowulf33** [sclasen/akka-persistence-dynamodb#7]
I suppose one could see the history for build.sbt to get an approximate timeline of the various release versions. But, it would be nice to tag the commits themselves with the release versions.

**Comment by rkuhn** [comment]
Thanks we’ll keep this in mind at the new home of this plugin: https://github.com/akka/akka-persistence-dynamodb (maintainership is being taken over by the Akka team now).

**Comment by rkuhn** [comment]
@sclasen close?

**Comment by sclasen** [comment]
:+1:  closing, please re-open if there are further questions.
